[package]
name = "octofhir-fhirpath"
version = "0.2.0"
edition = "2024"
authors = ["OctoFHIR Team <funyloony@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/octofhir/fhirpath-rs"
homepage = "https://github.com/octofhir/fhirpath-rs"
documentation = "https://docs.rs/octofhir-fhirpath"
description = "A high-performance FHIRPath implementation in Rust with comprehensive spec compliance"
readme = "README.md"
keywords = ["fhir", "fhirpath", "healthcare", "hl7", "parser"]
categories = ["parser-implementations", "data-structures", "science"]
include = [
    "src/**/*",
    "specs/**/*",
    "tests/**/*",
    "benches/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "CHANGELOG.md",
]
exclude = [
    "src/bin/extract_benchmark_metrics.rs",
]

[lib]
name = "octofhir_fhirpath"
path = "src/lib.rs"

[[bench]]
name = "fhirpath_benchmark"
harness = false



[[bin]]
name = "octofhir-fhirpath"
path = "src/bin/octofhir_fhirpath.rs"

[dependencies]
# Core dependencies
anyhow = "1.0.98"
base64 = "0.22.1"
chrono = { version = "0.4.41", features = ["serde"] }
dashmap = "6.1.0"
glob = "0.3"
hex = "0.4"
indexmap = "2.10.0"
log = "0.4.20"
lru = "0.16"
nom = "8.0.0"
nom_locate = "5.0.0-beta.5"
octofhir-ucum-core = "0.4.0"
octofhir-ucum-fhir = { version = "0.4.0", features = ["serde"] }
parking_lot = "0.12.4"
quick-xml = "0.38"
regex = "1.11.1"
rust_decimal = { version = "1.37.2", features = ["serde-with-str"] }
rustc-hash = "2.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
smallvec = { version = "1.11", features = ["serde"] }
thiserror = "2.0.12"
thread_local = "1.1"
unicode-xid = "0.2.6"

# Optional dependencies
colored = { version = "3.0.0", optional = true }
lsp-types = { version = "0.97.0", optional = true }
reqwest = { version = "0.12.22", features = ["json"], optional = true }
tokio = { version = "1.47.0", features = ["full"], optional = true }

# CLI dependencies
clap = { version = "4", features = ["derive"] }
human-panic = "2.0"

[dev-dependencies]
comfy-table = "7.0"
criterion = { version = "0.7.0", features = ["html_reports"] }
pretty_assertions = "1.4.1"
rstest = "0.26"
serde-xml-rs = "0.8"
colored = "3.0.0"
glob = "0.3"

[features]
default = []
lsp = ["lsp-types", "colored"]
network = ["reqwest", "tokio"]
diagnostics = ["colored"]
serde = []
terminal = ["colored"]
async-schema = ["tokio"]
never-enabled = []
