[package]
name = "fhirpath-rs"
version = "0.2.0"
edition = "2024"
authors = ["OctoFHIR Team <funyloony@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/octofhir/fhirpath-rs"
description = "A FHIRPath implementation in Rust"

[[bench]]
name = "tokenizer_only_benchmark"
harness = false

[[bench]]
name = "parser_benchmark"
harness = false


[[bench]]
name = "core_performance_benchmark"
harness = false

[[bin]]
name = "benchmark_server"
path = "src/benchmark_server.rs"


[dependencies]
fhirpath-parser = { path = "fhirpath-parser" }
fhirpath-core = { path = "fhirpath-core" }
criterion = { workspace = true }
tokio = { workspace = true }
warp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[workspace]
resolver = "3"
members = [
    "fhirpath-ast",
    "fhirpath-model",
    "fhirpath-diagnostics",
    "fhirpath-core",
    "fhirpath-parser",
    "fhirpath-registry",
    "fhirpath-evaluator",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["OctoFHIR Team <funyloony@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/octofhir/fhirpath-rs"
description = "A FHIRPath implementation in Rust"

[workspace.dependencies]
# Common dependencies for all crates
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
thiserror = "2.0.12"
anyhow = "1.0.98"
criterion = "0.7.0"
tokio = { version = "1.47.0", features = ["full"] }
warp = "0.3.7"
