name: Feature Request
description: Suggest a new feature or enhancement for fhirpath-rs
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see added.
      placeholder: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you need this feature? What problem does it solve?
      placeholder: Explain the use case and motivation...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: A detailed description of the feature and how it should work.
      placeholder: Describe the feature in detail...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used.
      placeholder: |
        Example usage:
        ```rust
        // Your example code here
        ```
      render: rust

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - FHIRPath Language Support
        - Performance Optimization
        - API Enhancement
        - Documentation
        - Developer Experience
        - Testing/Quality
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my work
        - Critical - Required for production use
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: What alternatives have you considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information...